import { Metadata } from "next"; //for ts support



export const metadata: Metadata = {
  title: {
    default: "Next.js learning by Venkata Sai",
    template: "%s | Venkata's learning",
    absolute: ""
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <p>Header</p>
        </header>

        {children}
        <footer style={{ backgroundColor: "ghostwhile", padding: "1rem" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
